### ISSUE TITLE
Show example in png?

### ISSUE THREAD

**Issue by cnlohr** [petabyt/font3x3#1]
Can you post a PNG sample of your font?  Zoomed in with pixel scaling so we can see the stylization clearly?

**Comment by petabyt** [comment]
You can get a pretty good idea of what it looks like from the demo.c program.

**Comment by petabyt** [comment]
![Screenshot at 2023-09-08 15-35-09](https://github.com/petabyt/font3x3/assets/32369330/076eea63-e805-4326-9a1e-7f289affea59)

**Comment by cnlohr** [comment]
You should put this on the main page so others can see it.
